spring:
  flyway:
    url: jdbc:h2:mem:mydatabasename
    user: sa
    password:
  datasource:
    url: jdbc:h2:mem:mydatabasename;DB_CLOSE_DELAY=-1;
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mail:
    host: smtp.gmail.com
    port: 587
    username: ramazan.ualdinuly@alumni.nu.edu.kz
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8082

rabbitmq:
  queue:
    email:
      name: email_queue
  exchange:
    email:
      name: email_exchange
  binding:
    email:
      name: email_routing_key

logging:
  level:
    org:
      springframework:
        amqp: DEBUG

